-intstyle "ise" -incremental -lib "secureip" -o "C:/Users/phil/Documents/GitHub/Calculator/testbench_isim_beh.exe" -prj "C:/Users/phil/Documents/GitHub/Calculator/testbench_beh.prj" "work.testbench" 
