-intstyle "ise" -incremental -lib "secureip" -o "C:/Users/phil/Documents/GitHub/Calculator/StackTest_isim_beh.exe" -prj "C:/Users/phil/Documents/GitHub/Calculator/StackTest_beh.prj" "work.StackTest" 
