-intstyle "ise" -incremental -lib "secureip" -o "C:/Users/seb/Desktop/Calculator-RFB/TestDesignTop_isim_beh.exe" -prj "C:/Users/seb/Desktop/Calculator-RFB/TestDesignTop_beh.prj" "work.TestDesignTop" 
